### ISSUE TITLE
Cycle Time query is broken

### ISSUE THREAD

**Issue by tovbinm** [faros-ai/faros-community-edition#110]
**Describe the bug**
Cycle Time query is broken

**To Reproduce**
1. Start Faros CE
2. Open Metabase UI, navigate to GitHub dashboard, click on Cycle Time
3. Open editor
4. See invalid query `"repositoryNam"` and `"mergedA"` are missing a letter each.

**Expected behavior**
The query should reference `"repositoryName"` and `"mergedAt"`

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/629845/164387085-cefbb011-bac4-48e9-b70a-def7ad2c49a5.png)
![image](https://user-images.githubusercontent.com/629845/164387106-8063c894-bc89-4c63-b6c5-51929b6f2843.png)

<img width="593" alt="Screen Shot 2022-04-20 at 21 56 32" src="https://user-images.githubusercontent.com/629845/164386904-863e7bbd-b9d6-4604-a6e0-9c8a90bc3bb0.png">

**Discussion**
https://faroscommunity.slack.com/archives/C0335HMN2NQ/p1650509861394399

**Comment by thomas-gerber** [comment]
Likely a regression caused by #107
