### ISSUE TITLE
Unable to install faros on windows OS

### ISSUE THREAD

**Issue by gouravsinghSeq** [faros-ai/faros-community-edition#173]
Error:
Error response from daemon: create tmp\airbyte_local: "tmp\\airbyte_local" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path

**Comment by thomas-gerber** [comment]
@gouravsinghSeq 

1. did you just run `./start.sh` without any changes to the `.env` file?
2. Specific OS version number?

**Comment by thomas-gerber** [comment]
Replicated the issue on a Windows 10 VM on Azure.
Installed docker with WSL 2. Got either this error, or an error on the sock volume.

**Comment by thomas-gerber** [comment]
Note that airbyte's [`docker-compose`](https://github.com/airbytehq/airbyte/blob/master/docker-compose.yaml) has drifted from our [copy](https://github.com/faros-ai/faros-community-edition/blob/main/airbyte-services.yaml), we may want to catch up first.
