### ISSUE TITLE
Kustomize doesn't support --load-restrictor LoadRestrictionsNone for remote resources

### ISSUE THREAD

**Issue by saviogl** [faros-ai/faros-community-edition#193]
**Describe the bug**
When trying to follow [these](https://github.com/faros-ai/faros-community-edition/blob/main/kube/README.md) instructions for deploying FarosCE in Kubernetes I'm getting the following issue:

```
Error: accumulating resources: accumulation err='accumulating resources from './faros': '/private/var/folders/vx/gbhv_rk12vq1zdf76bpn0nhh0000gq/T/kustomize-1233669672/kube/base/faros' must resolve to a file': recursed accumulation of path '/private/var/folders/vx/gbhv_rk12vq1zdf76bpn0nhh0000gq/T/kustomize-1233669672/kube/base/faros': loading KV pairs: env source files: [./config/.env]: security; file '/private/var/folders/vx/gbhv_rk12vq1zdf76bpn0nhh0000gq/T/kustomize-1233669672/kube/base/faros/config/.env' is not in or below '/private/var/folders/vx/gbhv_rk12vq1zdf76bpn0nhh0000gq/T/kustomize-1233669672/kube/base/faros'
```    

This is caused by the fact that we are trying to re-utilize the existing `.env` configuration file in the root by symlinking it to `kube/faros/config/.env`. When kustomize parses this files, it attempts to load a resource that is above the path of the  `kustomization.yaml` file in question which is typically prohibited for security reasons. However this can be bypassed with the flag `--load-restrictor LoadRestrictionsNone` and that often works but as we have just found out it doesn't seem to hold true for when resources are being referenced remotely like the command above.

Here's a reference to a [kustomize Github issue](https://github.com/kubernetes-sigs/kustomize/issues/4052) touching on the unexpected behavior.

If one clones the repository and runs

```
kustomize build --load-restrictor LoadRestrictionsNone kube/base
```

things work properly, and the --load-restrictor flag is respected

**To Reproduce**
1. Install [kustomize](https://kubectl.docs.kubernetes.io/installation/kustomize/)
2. From a terminal execute `kustomize build --load-restrictor LoadRestrictionsNone https://github.com/faros-ai/faros-community-edition/kube/base`

**Expected behavior**
FarosCE K8s manifests are rendered correctly

**Screenshots and logs**
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/8523281/176479620-faca01e4-f3ed-4705-97c9-9d201f1c7d8f.png">

**Deployment**
* Kustomize 4.5.5

**Comment by thomas-gerber** [comment]
I propose we copy the .env file for now until there is a workaround?
