### ISSUE TITLE
Cant add my github repo to airbyte

### ISSUE THREAD

**Issue by abel-yakubu** [faros-ai/faros-community-edition#233]
I filled in my personal auth token and github repo to airbyte. But i get the error in the screenshot attached

<img width="1143" alt="Screenshot 2022-10-20 at 10 30 51" src="https://user-images.githubusercontent.com/87363571/197150442-9cac58e7-5158-43d8-93a8-6d40d0fe9434.png">

Please how i can resolve this

**Comment by thomas-gerber** [comment]
@abel-yakubu this is likely not the error; could you send the whole log / look further below?
For faster assistance, you can join us on our [slack](https://community.faros.ai/docs/slack).
