### ISSUE TITLE
Jira Issues not linking to Epics

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/faros-community-edition#272]
**Describe the bug**
The tms_Task converted from a Jira issue that belongs to a Jira epic does not link to the tms_Epic (or to the parent tms_Task). Introduced in destination `0.4.49`.

**To Reproduce**
Steps to reproduce the behavior (for Faros employees):
1. Deploy Faros CE
2. Set Faros destination version to `0.4.48` in the Airbyte Setting screen
3. Sync the TEST jira project (12 months)
4. check TEST-20 in tms_Task; it does link to the TEST-18 corresponding epic
5. Set Faros destination version to `0.4.49` in the Airbyte Setting screen
6. Reset the Jira connection
7. Sync the TEST jira project (12 months)
8. check TEST-20 in tms_Task; it does NOT link to the TEST-18 corresponding epic

**Comment by ted-faros** [comment]
@thomas-gerber do you happen to have the test TEST jira project as a file?  If not, I can run the source to extract it.

**Comment by thomas-gerber** [comment]
I do not
