### ISSUE TITLE
GitLab sync fails if project doesn't have CI/CD enabled

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/faros-community-edition#277]
**Describe the bug**
When a project does not have CI/CD activated, the sync will fail because of 403 API errors during the pipeline stream.

**Screenshots and logs**
If applicable, add screenshots and logs to help explain your problem.

<img width="1367" alt="Screenshot 2023-02-01 at 6 56 26 PM" src="https://user-images.githubusercontent.com/1591609/216220343-81cd8742-287e-4f7f-972e-7dbd5cc75ae3.png">

```
403 Client Error: Forbidden for url: https://gitlab.com/api/v4/projects/[redacted]/pipelines?per_page=50&updated_after=2023-01-03T02%3A49%3A24Z
```

**Comment by thomas-gerber** [comment]
@cjwooo would it be a good idea to silently ignore streams that produce 403s?

**Comment by cjwooo** [comment]
I think we should still error in cases like this, so that the connector will still signal to the user that there could be an authn/z issue. If the user determines afterwards that the cause was a feature not being enabled, e.g. CI/CD for a GitLab project, they should explicitly disable the stream.
