### ISSUE TITLE
Missing Jira Additional Fields

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/faros-community-edition#281]
**Describe the bug**
Jira Additional Fields are not written to Faros.

**To Reproduce**
1. Configure your Jira source `Additional Fields` and save
2. Sync
3. In Hasura, do the following query: 
```
query MyQuery {
  tms_Task(where: {uid: {_eq: "TEST-1"}}) {
    additionalFields
    name
  }
}
```
4. The additional field is missing.
Note that in Metabase, the additionalField column in tms_Task will only display in the detail view (when you look at the record).

Can be reproduced on our `TEST` project with custom field `customfield_10049` (`testcustom` field). `TEST-1` should have `foo` in there. Jira source is the community one on 0.2.20.

**Comment by justynclark** [comment]
@thomas-gerber  I have the exact same issue.  Is there a workaround? Thanks.

**Comment by thomas-gerber** [comment]
As best as I can tell (when connecting that source into the Airbyte E2E Testing destination), the custom fields are not returned with the issue by the community source, which is currently pegged at 0.2.21 when Faros is provisioned (pretty old).

You could try to update to the latest jira community source (1.3.0) in Settings > Source, check the source config and the destination config. The custom fields are all fetched and properly stored Faros side. I also see lots of errors in the sync which I am not sure about - although it looks OK in metabase.
