### ISSUE TITLE
Azure DevOps support in upcoming release 

### ISSUE THREAD

**Issue by michaeljwright** [faros-ai/faros-community-edition#291]
I just wanted to ask when the next release is scheduled for? There doesn’t appear to be any info about this.

I’ve seen that there will be Azure DevOps / Pipelines support in upcoming release and really want to test out your project.

**Comment by thomas-gerber** [comment]
There is a way to ingest Azure Pipelines today thanks to our [connector](https://github.com/faros-ai/airbyte-connectors/tree/main/sources/azurepipeline-source), I will write a guide shortly and post it here. We will add it to the list of canned source once we migrate to Airbyte v40 in a few weeks.

**Comment by michaeljwright** [comment]
Ok thanks @thomas-gerber ! And thanks for responding.  What about Azure DevOps for Git/repo support?  I just looked at the connector sources and there appears to be [Azure Repos](https://github.com/faros-ai/airbyte-connectors/tree/main/sources/azure-repos-source) but I don't think that's the same thing. Cheers.
