### ISSUE TITLE
kube deployment kustomize seem not working properly

### ISSUE THREAD

**Issue by kholisrag** [faros-ai/faros-community-edition#335]
**Describe the bug**
kube deployment kustomize seem not working properly. with the current kustomize

**To Reproduce**
1. Install using the kustomize
2. Follow the step by step initiation
3. In the step of airbyte - github sources the `save changes and test` will always error, ref: https://community.faros.ai/docs/quickstart-step-2

I'm using GKE 1.27

**Expected behavior**
the step should have no error

**Screenshots and logs**
When I retry multiple times below is the result : 
![2024-03-04_14-58-25](https://github.com/faros-ai/faros-community-edition/assets/4683704/56f8bcbb-945a-42a3-a307-770ae9ba841d)
![2024-03-04_15-14-55](https://github.com/faros-ai/faros-community-edition/assets/4683704/4fc0c96f-fedb-466b-a4e6-599f279009bb)
![2024-03-04_15-15-14](https://github.com/faros-ai/faros-community-edition/assets/4683704/04bc6e35-e446-4752-a9b0-a0666a4e66a0)

After retry multiple time seem success but I got stuck at triggering the github sync now
![2024-03-04_15-20-05](https://github.com/faros-ai/faros-community-edition/assets/4683704/9a536575-6e56-40f4-80ad-c3fe20c7f045)
![2024-03-04_15-20-20](https://github.com/faros-ai/faros-community-edition/assets/4683704/5596100b-8861-42a9-9171-adab62ad72db)
![2024-03-04_15-20-31](https://github.com/faros-ai/faros-community-edition/assets/4683704/1cd94bc9-a566-423a-9ca0-35b4c564eca7)

Any Idea on whats going on?

**Deployment**
* If cloud, GKE 1.27 and latest version

**Comment by thomas-gerber** [comment]
I am confused what S3 has to do with anything here.
@saviogl any idea?
