### ISSUE TITLE
[doubt] update airbyte

### ISSUE THREAD

**Issue by mavis-martins** [faros-ai/faros-community-edition#337]
How can I update airbyte's version through faros .env?

I'm already tried to change by enviroment variables putting VERSION=0.53.0.

If can someone help me, I'd be thankfull

**Comment by thomas-gerber** [comment]
That is the main way, and when you run the docker compose up (or start scrit), it should fetch that Airbyte version. Wasn't that the case for you?
Please note that the init of Faros, that configures all those systems (Airbyte, Hasura, Metabase, DBs) was only tested on 0.40.9, I do not know if it will work on 0.53.0 without adjustments.
