### ISSUE TITLE
Question: how to disable SSL Verification when adding a Connector

### ISSUE THREAD

**Issue by claudious05** [faros-ai/faros-community-edition#353]
Im Trying to add datasources, and I get an error cause there are no SSL Certs for my Data Source in Faros.
How can I disable the SSL Verification or import the certs?

**Comment by thomas-gerber** [comment]
> Im Trying to add datasources, and I get an error cause there are no SSL Certs for my Data Source in Faros. How can I disable the SSL Verification or import the certs?

Which source are you adding?

**Comment by claudious05** [comment]
Hey, thank you for the answer. I have successfully installed the required ssl certs and I get no more errors, but nos the source which is by the way gitlab loads a lot of time without getting any message or error. Have someone expirienced this already?

**Comment by thomas-gerber** [comment]
Not that I can remember.
The GitLab source is the public one from the airbyte community. Maybe it is an issue with the fact that our default packaging here is old (i.e. we package a now old version of Airbyte, and old version of the GitLab source).
