### ISSUE TITLE
n8n initialization error - "/home/node/.n8n/config". It does not seem to be valid JSON."

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/faros-community-edition#45]

**Comment by thomas-gerber** [comment]
We have still found instance of this error after #47 .

**Comment by tovbinm** [comment]
Temp fix explained here - https://community.faros.ai/docs/gotchas#n8n-initialization-error

**Comment by thomas-gerber** [comment]
We believe #94 removes the race condition causing this issue.
